services:
  - type: web
    name: profptiy-backend
    env: node
    plan: free
    buildCommand: "npm install && npm run build"
    startCommand: "npx prisma migrate deploy && npm start"
    rootDir: backend
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
